# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: check
    displayName: Check code
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: ci/check.yml
    condition: and(always(), eq(variables['Build.Reason'], 'PullRequest'))
