# This compose file will deploy the services, and bootup a mongo server.
# Local `/opt/cello/mongo` will be used for the db storage.
#  dashbard: dashbard service of cello, listen on 8080
#  app: app service of cello, listen on 80
#  nginx: front end
#  mongo: mongo db

version: '2'
services:
  # cello dashbard service
  build-js:
    image: node
    container_name: build-js
    volumes:  # This should be removed in product env
      - ./src/themes/react/static:/app
    command: bash -c "cd /app && npm run build"
