# This compose file will deploy the services, and bootup a postgres server.

#
# SPDX-License-Identifier: Apache-2.0
#

#  cello-dashboard: dashboard service for cello
#  cello-api-engine: api engine service of cello to provide RESTful APIs, listen on 8080
#  cello-postgres: postgres db 

version: '3.2'
services:

  # pg database
  cello-postgres:
    image: postgres:11.1
    hostname: cello-postgres
    container_name: cello-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=api_engine
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - /opt/cello/pgdata:/var/lib/postgresql/data

# api engine service of cello 
  cello-api-engine:
    image: hyperledger/cello-api-engine
    container_name: cello-api-engine
    hostname: cello-api-engine
    restart: unless-stopped
    links:
      - cello-postgres
    environment:
      - DB_NAME=api_engine
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_HOST=cello-postgres
      - DB_PORT=5432
      - DEBUG=True
    ports:
      - "8080:8080"
    # volumes:
     # - /opt/fabric:/opt/fabric
     # - /etc/localtime:/etc/localtime 
 
    


